# Generated by Django 5.1.7 on 2025-04-02 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ramka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=500)),
                ('grubosc', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'ramka',
                'verbose_name_plural': 'ramki',
            },
        ),
        migrations.CreateModel(
            name='Szyba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=500)),
                ('grubosc', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'szyba',
                'verbose_name_plural': 'szyby',
            },
        ),
        migrations.CreateModel(
            name='Glasstwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramka1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog2.ramka')),
                ('szyba1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glasstwo_szyba1_set', to='catalog2.szyba')),
                ('szyba2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glasstwo_szyba2_set', to='catalog2.szyba')),
            ],
        ),
        migrations.CreateModel(
            name='Glassthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramka1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glassthree_ramka1_set', to='catalog2.ramka')),
                ('ramka2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glassthree_ramka2_set', to='catalog2.ramka')),
                ('szyba1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glassthree_szyba1_set', to='catalog2.szyba')),
                ('szyba2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glassthree_szyba2_set', to='catalog2.szyba')),
                ('szyba3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glassthree_szyba3_set', to='catalog2.szyba')),
            ],
        ),
        migrations.CreateModel(
            name='Glassone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szyba1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog2.szyba')),
            ],
            options={
                'verbose_name': 'pakiet jednoszybowy',
                'verbose_name_plural': 'pakiety jednoszybowe',
            },
        ),
    ]
