# Generated by Django 5.1.7 on 2025-04-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glassthree',
            options={'verbose_name': 'pakiet trzyszybowy', 'verbose_name_plural': 'pakiety trzyszybowe'},
        ),
        migrations.AlterModelOptions(
            name='glasstwo',
            options={'verbose_name': 'pakiet dwuszybowy', 'verbose_name_plural': 'pakiety dwuszybowe'},
        ),
        migrations.AlterField(
            model_name='ramka',
            name='grubosc',
            field=models.DecimalField(decimal_places=2, max_digits=5, unique=True),
        ),
        migrations.AlterField(
            model_name='ramka',
            name='nazwa',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
