# Generated by Django 5.1.7 on 2025-04-02 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog2', '0002_alter_glassthree_options_alter_glasstwo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glassone',
            name='szyba1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog2.szyba', unique=True),
        ),
        migrations.AlterField(
            model_name='glasstwo',
            name='ramka1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glasstwo_ramka1_set', to='catalog2.ramka'),
        ),
        migrations.AlterField(
            model_name='ramka',
            name='grubosc',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='szyba',
            name='nazwa',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AddConstraint(
            model_name='glassthree',
            constraint=models.UniqueConstraint(fields=('szyba1', 'ramka1', 'szyba2', 'ramka2', 'szyba3'), name='unique_glassthree_combination'),
        ),
        migrations.AddConstraint(
            model_name='glasstwo',
            constraint=models.UniqueConstraint(fields=('szyba1', 'ramka1', 'szyba2'), name='unique_glasstwo_combination'),
        ),
    ]
