# Generated by Django 5.1.7 on 2025-04-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog2', '0003_alter_glassone_szyba1_alter_glasstwo_ramka1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramka',
            name='nazwa',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='szyba',
            name='nazwa',
            field=models.CharField(max_length=500),
        ),
    ]
