# Generated by Django 5.1.7 on 2025-04-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog2', '0004_alter_ramka_nazwa_alter_szyba_nazwa'),
    ]

    operations = [
        migrations.AddField(
            model_name='szyba',
            name='image',
            field=models.ImageField(default=0, upload_to='media/'),
            preserve_default=False,
        ),
    ]
