# Generated by Django 4.2 on 2025-04-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog2', '0006_alter_szyba_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='glassthree',
            name='gfactor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glassthree',
            name='rw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glassthree',
            name='ufactor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
