# Generated by Django 4.2 on 2025-04-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog2', '0007_glassthree_gfactor_glassthree_rw_glassthree_ufactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='glassone',
            name='gfactor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glassone',
            name='rw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glassone',
            name='ufactor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glasstwo',
            name='gfactor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glasstwo',
            name='rw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glasstwo',
            name='ufactor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
